import './globals.css';
import type { Metadata } from 'next';
import Navbar from './Components/Navbar';
import Footer from './Components/Footer';
import './scss/styles.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
